Problem: version not updated to v0.0.10 (fix #241)
cronos-labs/play-unreal-plugin pull request #243
Opened 2023-01-09 00:25 UTC by leejw51crypto

Solution: new release to v0.0.10

2023-01-09 02:48 UTC, damoncro requested changes
CHANGELOG.md: play-cpp-sdk should be `v0.0.14-alpha`.

2023-01-10 00:52 UTC, leejw51crypto commented
ok

2023-01-10 01:12 UTC, tomtau approved these changes

2023-01-10 01:27 UTC, damoncro approved these changes

2023-01-11 01:30 UTC, merged